CREATE TABLE `persons` (
    `id`                  BIGINT       NOT NULL AUTO_INCREMENT,
    `name`                VARCHAR(100) NOT NULL,
    `nick_name`           VARCHAR(255) DEFAULT NULL,
    `birth_date`          DATE         DEFAULT NULL,
    `naturalness`         VARCHAR(255) DEFAULT NULL,
    `origin_city`         VARCHAR(255) DEFAULT NULL,
    `sexy_enum`           TINYINT      DEFAULT NULL,
    `marital_status_enum` TINYINT      DEFAULT NULL,
    `cpf`                 VARCHAR(14)  DEFAULT NULL,
    `rg`                  VARCHAR(20)  DEFAULT NULL,
    `orgao_expeditor`     VARCHAR(50)  DEFAULT NULL,
    `professional`        VARCHAR(255) DEFAULT NULL,
    `company_work`        VARCHAR(255) DEFAULT NULL,
    `education_enum`      TINYINT      DEFAULT NULL,
    `member`              TINYINT(1)   NOT NULL DEFAULT 0,
    `created_at`          DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at`          DATETIME     DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    `deleted_at`          DATETIME     DEFAULT NULL,
    `street`              VARCHAR(255) DEFAULT NULL,
    `number`              VARCHAR(20)  DEFAULT NULL,
    `complement`          VARCHAR(255) DEFAULT NULL,
    `neighborhood`        VARCHAR(255) DEFAULT NULL,
    `city`                VARCHAR(255) DEFAULT NULL,
    `state`               VARCHAR(2)   DEFAULT NULL,
    `cep`                 VARCHAR(9)   DEFAULT NULL,
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
